### ISSUE TITLE
TypeError in models.py

### ISSUE THREAD

**Issue by eriktelepovsky** [yunojuno/django-package-monitor#2] opened 2015-12-04 13:39 UTC
Result of ``python manage.py refresh_packages --clean --local --remote``:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/package_monitor/management/commands/refresh_packages.py", line 83, in handle
    remote()
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/package_monitor/management/commands/refresh_packages.py", line 40, in remote
    pv.update_from_pypi()
  File "/Users/erik/env/cargo/lib/python2.7/site-packages/package_monitor/models.py", line 117, in update_from_pypi
    self.licence = package_licence(info)[:100]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by hugorodgerbrown** [comment] 2015-12-04 14:07
This looks like a PyPI package that has no licence in the API response - which is not something I've ever seen before. Could you post your `requirements.txt` so that I can reproduce the issue?

**Comment by hugorodgerbrown** [comment] 2015-12-05 19:58
Looking at this again - it's not the missing licence, it's missing the 'info' block in the PyPI response.

If I knew the package name I could debug this:

```python
url = "http://pypi.python.org/pypi/%s/json" % package
requests.get(url).json()
```

**Comment by eriktelepovsky** [comment] 2015-12-06 09:16
Sure, here is my requirements.txt:

```
Django==1.8.4
Pillow==2.9.0
django-breadcrumbs==1.1.3
django-cerberus==0.3.2
django-clever-selects==0.6.9
-e git+https://github.com/maraujop/django-crispy-forms#egg=django_crispy_forms-dev
django-cron==0.4.3
-e git+https://github.com/saz/django-dajax#egg=dajax
django-dajaxice==0.7
django-datatables-view==1.12.1
django-debug-toolbar==1.3.2
django-detective==0.5.1
django-developer-toolkit==0.4.0
django-extensions==1.5.5
django-filter==0.10.0
django-formtools==1.0
django-form-utils==1.0.2
django-hooks==0.1.3
django-impersonate==0.9.1
django-mobile==0.5.0
django-modeltranslation==0.10
django-money==0.7.0
django-pdf-tables==0.3.0
django-permissions-widget==1.4.0
django-polymorphic==0.7.1
django-pragmatic==1.6.1
django-rosetta==0.7.6
django-session-security==2.2.4
django-smtp-ssl==1.0
django-solo==1.1.0
djangorestframework==3.1.3
easy-thumbnails==2.2
fpdf==1.7.2
microsofttranslator==0.5
ordereddict==1.1
pip-tools==0.3.6
polib==1.0.6
progressbar==2.3
pyBarcode==0.7
py-moneyed==0.5.0
python-dateutil==2.4.2
python-ldap==2.4.20
python-pragmatic==0.4.2
psycopg2==2.6.1
pytz==2015.4
requests==2.7.0
six==1.9.0
sqlparse==0.1.15
suds==0.4
wsgiref==0.1.2
xlwt==1.0.0
```

**Comment by hugorodgerbrown** [comment] 2015-12-06 09:56
Thanks. It was `django-form-utils` that was returning None from PyPI as the licence info. I've pushed a fix (https://github.com/yunojuno/django-package-monitor/commit/e313f0d7dbc28fedcef63cdf8e2f0be6b6ff9821) for this. Will look at the other issues before releasing an update.

**Closed by hugorodgerbrown** 2015-12-06 09:56 UTC
